src/SonOfCod/Models/ApplicationDbContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace SonOfCod.Models
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public string ConnectionString = "Server=(localdb)\\MSSQLLocalDB;Database=SonOfCod;Trusted_Connection=True;MultipleActiveResultSets=true"; //For unit tests
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Photo> Photos { get; set; }

        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions options) : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(ConnectionString);

        }
    }
}

src/SonOfCod/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace SonOfCod.Models
{
    public class ApplicationUser : IdentityUser
    {
    }
}

src/SonOfCod/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SonOfCod.Models
{
    [Table("Contacts")]
    public class Contact
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string FullName()
        {
            return String.Format("{0} {1}", FirstName, LastName);
        }

    }
}

src/SonOfCod/Models/Photo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SonOfCod.Models
{
    [Table("Photos")]
    public class Photo
    {
        public Photo()
        {
        }
        public Photo(string name, byte[] data)
        {
            Name = name;
            Data = data;
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }

        public string getImage()
        {
            // Convert byte data array to string that '<img src=' can read
            var base64File = Convert.ToBase64String(Data);
            return String.Format("data:image/gif;base64,{0}", base64File);
        }
    }
}

src/SonOfCod/ViewModels/LoginViewModel.cs
namespace SonOfCod.ViewModels
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

src/SonOfCod/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SonOfCod.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

src/SonOfCod/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SonOfCod.Models;
using SonOfCod.ViewModels;
using System.Threading.Tasks;

namespace SonOfCod.Controllers
{
    public partial class AccountController : BaseController
    {
        public AccountController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext db) : base(userManager, signInManager, db)
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Signup(RegisterViewModel model)
        {
            var user = new ApplicationUser { UserName = model.Email };
            IdentityResult result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                return RedirectToAction("Login");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: true, lockoutOnFailure: false);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/SonOfCod/Controllers/BaseController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SonOfCod.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SonOfCod.Controllers
{
    public abstract partial class BaseController : Controller
    {

        public readonly ApplicationDbContext _db;
        public readonly UserManager<ApplicationUser> _userManager;
        public readonly SignInManager<ApplicationUser> _signInManager;

        //public static Photo Boats { get; set; }
        //public static Photo Nets { get; set; }

        public BaseController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
            //Boats = _db.Photos.FirstOrDefault(ph => ph.Name == "Boats");
            //Nets = _db.Photos.FirstOrDefault(ph => ph.Name == "Nets");

        }

    }
}

src/SonOfCod/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using SonOfCod.Models;
using Microsoft.AspNetCore.Http;
using System.IO;


namespace SonOfCod.Controllers
{
    public partial class HomeController : BaseController
    {

        public HomeController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext db) : base(userManager, signInManager, db)
        {
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UploadPhoto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UploadPhoto(string Name, IFormFile Data)
        {
            byte[] photoArray = new byte[0];

            if (Data != null)
            {
                using (Stream fileStream = Data.OpenReadStream())
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    fileStream.CopyTo(memoryStream);
                    photoArray = memoryStream.ToArray();
                }
            }

            Photo newPhoto = new Photo(Name, photoArray);

            _db.Photos.Add(newPhoto);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/SonOfCod/Controllers/MailingListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using SonOfCod.Models;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;
using System.Linq;


namespace SonOfCod.Controllers
{
    public partial class MailingListController : BaseController
    {
        public MailingListController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext db) : base(userManager, signInManager, db)
        {
        }

        public IActionResult Join()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Join(Contact newContact)
        {
            _db.Contacts.Add(newContact);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult List()
        {
            List<Contact> allContacts = _db.Contacts.ToList();
            return View(allContacts);
        }
    }
}

src/SonOfCod/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}

@*<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center teal-text text-lighten-2">Parallax Template</h1>
            <div class="row center">
                <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
            </div>
            <div class="row center">
                <a class="btn-large waves-effect waves-light blue darken-4">Get Started</a>
            </div>
            <br><br>
        </div>
    </div>
    <div class="parallax"><img src="~/Content/img/boats.png" alt="Fishing Boats"></div>
</div>*@
<div class="section white">
    <div class="row container">
        <h2 class="header grey-text text-darken-3">Welcome</h2>
        <p class="grey-text text-darken-3 lighten-3">Son of Cod Seafood is a family owned and operated fishing company. We strive to provide the freshest, cleanest, and most sustainable fish and seafood products at affordable prices. We have a fleet of over four ships allowing us to catch a minimum of twenty fish per day! To receive regular updates about our daily catch and other important stories, join our mailing list.</p>
        <a asp-controller="MailingList" asp-action="Join" class="btn amber lighten-1">Join Our Mailing List</a>
    </div>
</div>

src/SonOfCod/Views/Home/UploadPhoto.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Upload Photo";
}

<h3>Upload Photo</h3>

<form asp-controller="Home" asp-action="UploadPhoto" method="post" enctype="multipart/form-data">
    <div class="input-field">
        <label for="Name">Name</label>
        <input type="text" id="Name" name="Name" required />
    </div>
    <div class="file-field input-field">
        <div class="btn amber lighten-1">
            <span>File</span>
            <input type="file" name="Data">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" type="text" placeholder="Upload image file">
        </div>
    </div>
    <input type="submit" class="waves-effect waves-light btn blue darken-4" value="Upload" />
</form>
<br /><br />

src/SonOfCod/Views/MailingList/Join.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Mailing List";
}

@model SonOfCod.Models.Contact

<h3>Join Mailing List</h3>

<form asp-controller="MailingList" asp-action="Join" method="post">
    <div asp-validation-summary="ModelOnly" class="red-text"></div>
    <div class="row">
        <div class="input-field col s12">
            <input asp-for="Email">
            <span asp-validation-for="Email" class="red-text"></span>
            <label asp-for="Email"></label>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s6">
            <input asp-for="FirstName">
            <span asp-validation-for="FirstName" class="red-text"></span>
            <label asp-for="FirstName">First Name (optional)</label>
        </div>
        <div class="input-field col s6">
            <input asp-for="LastName">
            <span asp-validation-for="LastName" class="red-text"></span>
            <label asp-for="LastName"> Last Name (optional)</label>
        </div>
    </div>

    <input type="submit" class="waves-effect waves-light btn blue darken-4" value="Submit" />
</form>
<br /><br />

src/SonOfCod/Views/MailingList/List.cshtml
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Mailing List";
}

@using SonOfCod.Models
@model List<Contact>

<h2>Mailing List</h2>

<ul class="collection">
 
@foreach (var contact in Model)
{
    <li class="collection-item avatar">
        <i class="material-icons circle amber lighten-1">perm_identity</i>
        <span class="title">
            @if (contact.FirstName != null && contact.LastName != null)
            {
                @contact.FullName()
            }
        </span>
        <br />
        <p class="valign-center">
            <i class="tiny material-icons">email</i>
            &nbsp;@contact.Email
        </p>
    </li>
}
</ul>

src/SonOfCod/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using System.Security.Claims
@using SonOfCod.Controllers
@using SonOfCod.Models
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @* Materialize/CSS *@
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/Content/css/materialize.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/styles.css" rel="stylesheet" type="text/css"/>
    @* jQuery *@
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    @* Materialize JS *@
    <script src="~/Content/js/materialize.js"></script>
    @* Validation Scripts *@
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/js/materialize-jquery.js" type="text/javascript"></script>
</head>
    <body>
        <nav class="white">
            <div class="nav-wrapper">
                <div class="container">
                    <a asp-controller="Home" asp-action="Index"
                       class="brand-logo blue-text darken-4">Son of Cod Seafood</a>
                    <ul class="right hide-on-med-and-down">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><span class="grey-text">@User.Identity.Name</span></li>
                            <li><a asp-controller="Account" asp-action="Logout">Log Out</a></li>
                            <li><a asp-controller="MailingList" asp-action="List">Mailing List</a></li>


                        }
                        else
                        {
                            <li><a asp-controller="Account" asp-action="Signup">Signup</a></li>
                            <li><a asp-controller="Account" asp-action="Login">Log In</a></li>
                        }
                    </ul>
                    <a href="#" data-activates="hamburger" class="button-collapse right"><i class="material-icons">menu</i></a>
                    <ul class="side-nav" id="hamburger">
                        @if(User.Identity.IsAuthenticated)
                        {   
                            <li><a asp-controller="Account" asp-action="Logout">Log Out</a></li>
                            <li><a asp-controller="MailingList" asp-action="List">Mailing List</a></li>

                        }
                        else
                        {
                            <li><a asp-controller="Account" asp-action="Signup">Signup</a></li>
                            <li><a asp-controller="Account" asp-action="Login">Log In</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

        @* Parallax one *@
        <div id="index-banner" class="parallax-container">
            <div class="parallax"><img src="~/Content/img/Boats.png" alt="Fishing Boats"></div>
        </div>
        @* Main Body *@
        <div class="container">
         @RenderBody()
        </div>

        @* Parallax two *@
        <div class="parallax-container">
            <div class="parallax"><img src="~/Content/img/Nets.png" alt="Nets"></div>
        </div>


        <footer class="page-footer white">
            <div class="footer-copyright">
                <div class="container right-align">
                    <span class="grey-text darken-1">© 2017 Son of Cod Seafood. All rights reserved.</span>
                </div>
            </div>
        </footer>
    </body>
</html>